### ISSUE TITLE
Вертикальные поля рамки

### ISSUE THREAD

**Issue by Igorbunow** [kutelev/gost_forms#3]
Здравствуйте! 
Возможно ли в текущей версии задавать значение вертикальных полей рамки, например, перв. применение?

**Comment by kutelev** [comment]
Если я правильно понял вопрос, то ответ - да, можно.

Пример документа: https://gitlab.com/kutelev/gost_forms/-/jobs/711907270/artifacts/file/%D0%90%D0%91%D0%92%D0%93.123456.001%20(%D0%9A%D0%B2%D0%B0%D0%BD%D1%82%D0%BE%D0%B2%D1%8B%D0%B9%20%D1%82%D0%B5%D0%BB%D0%B5%D0%BF%D0%BE%D1%80%D1%82%D0%B0%D1%82%D0%BE%D1%80)/%D0%90%D0%91%D0%92%D0%93.123456.001%20(%D0%A1%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F)/%D0%90%D0%91%D0%92%D0%93.123456.001%20(%D0%A1%D0%BF%D0%B5%D1%86%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%86%D0%B8%D1%8F).pdf

Способ достижения результата: https://gitlab.com/kutelev/gost_forms/-/commit/c9baed64e9806a72390ded3af84d9aff9f0ee491

Заполнить можно любые поля (ну кроме тех которые предполагается заполнять руками) согласно их нумерации в соответствии с ГОСТ.

![image](https://user-images.githubusercontent.com/21998548/91734926-c42bfd00-ebd5-11ea-88ba-2a4a7ddfb6dc.png)

Например `Перв. применение` - это поле номер 25.

**Comment by kutelev** [comment]
Считаю, что ответ на вопрос дан.
